# .github/workflows/deploy-cpanel-sftp.yml
name: Deploy to cPanel via SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optionally build a _site folder like Pages; if not needed, deploy repo root
      # - run: |
      #     rsync -a --delete --exclude 'media/**' --exclude 'uploads/**' ./ ./_site/

      - name: Deploy via SSH (scp)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: 22
          source: .
          target: ./public_html/
